### ISSUE TITLE
Shitan token image is missing

### ISSUE THREAD

**Issue by tatsumasagc** [tianevitt/tianzes-gauntlight-extras#7]

**Comment by tianevitt** [comment]
I did not include tokens for default actors like Shaitan and the hags. In my own game, I have them pointing to the Token Bestiaries module, but I did not think to include it as a dependency.

Since I don't want to do that, I'll work on some tokens for my next update, hopefully before the weekend.

As a temporary workaround, you can find the art at https://2e.aonprd.com/?AspxAutoDetectCookieSupport=1 and tokenize them using https://rolladvantage.com/tokenstamp/.

**Comment by tianevitt** [comment]
Added portraits and tokens for Shaitan and the hags on the 7th level. Thanks for the suggestion!
